const TOGGLE_BOOL = 'TOGGLE_BOOL'
const UPDATE_PET = 'UPDATE_PET'
const SET_STEP = 'SET_STEP'
const NEXT_STEP = 'NEXT_STEP'
const PREV_STEP = 'PREV_STEP'
const UPDATE_SELECTION = 'UPDATE_SELECTION'

export default {
  TOGGLE_BOOL,
  UPDATE_PET,
  SET_STEP,
  NEXT_STEP, 
  PREV_STEP,
  UPDATE_SELECTION
}