const UPDATE_PET = 'UPDATE_PET'
const UPDATE_PETNAME = 'UPDATE_PETNAME'
const UPDATE_PETTYPE = 'UPDATE_PETTYPE'
const SET_STEP = 'SET_STEP'
const NEXT_STEP = 'NEXT_STEP'
const PREV_STEP = 'PREV_STEP'
const UPDATE_SELECTION = 'UPDATE_SELECTION'
const RESET = 'RESET'

export default {
  UPDATE_PET,
  UPDATE_PETNAME,
  UPDATE_PETTYPE,
  SET_STEP,
  NEXT_STEP, 
  PREV_STEP,
  UPDATE_SELECTION,
  RESET
}